# Generated by Django 3.0.4 on 2020-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(default='', upload_to='file_attachments/'),
        ),
    ]
