# Generated by Django 3.0.4 on 2020-05-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200430_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Choice 1'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Choice 2'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Choice 3'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice4',
            field=models.CharField(blank=True, max_length=50, verbose_name='Choice 4'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=50, verbose_name='question'),
        ),
    ]
