# Generated by Django 3.0.4 on 2020-05-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20200502_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_four',
            field=models.CharField(blank=True, max_length=50, verbose_name='Choice 4'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_one',
            field=models.CharField(blank=True, max_length=50, verbose_name='Choice 1'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_three',
            field=models.CharField(blank=True, max_length=50, verbose_name='Choice 3'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_two',
            field=models.CharField(blank=True, max_length=50, verbose_name='Choice 2'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=50, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='crud.Question'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
