# Generated by Django 3.0.4 on 2020-05-06 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20200502_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ClassName')),
            ],
        ),
    ]
