# Generated by Django 3.0.4 on 2020-05-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20200517_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='crud.Choice', verbose_name=''),
        ),
    ]
