# Generated by Django 3.0.4 on 2020-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_auto_20200521_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Choice'),
        ),
    ]
