# Generated by Django 3.0.4 on 2020-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_choice_question_quiz_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='text',
            field=models.CharField(max_length=30, verbose_name='Quiz Title'),
        ),
    ]
