# Generated by Django 3.0.4 on 2020-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20200502_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.CharField(max_length=50, verbose_name='Correct Answer'),
        ),
    ]
