# Generated by Django 3.0.4 on 2020-05-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='due',
            field=models.DateTimeField(),
        ),
    ]
