# Generated by Django 3.0.4 on 2020-05-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20200507_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_four',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_three',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_two',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=100, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Quiz Title'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='question')),
                ('correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Question')),
            ],
        ),
    ]
