# Generated by Django 3.0.4 on 2020-05-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_auto_20200517_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
