# Generated by Django 3.0.5 on 2020-06-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_useranswer_quiz'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
    ]
