# Generated by Django 3.0.5 on 2020-06-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0022_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
    ]
