# Generated by Django 3.0.5 on 2020-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0026_auto_20200628_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
